In [1]:
import numpy as np
import tensorflow as tf
import torch

In [3]:
x = np.array([[12, 13, 24], [21, 32, 41]])
x_tf = tf.Variable([[12, 13, 24], [21, 32, 41]])
x_pt = torch.tensor([[12, 13, 24], [21, 32, 41]])

In [4]:
x

array([[12, 13, 24],
       [21, 32, 41]])

In [5]:
# Scalar addition to matrix.
x + 2

array([[14, 15, 26],
       [23, 34, 43]])

In [6]:
x * 2

array([[24, 26, 48],
       [42, 64, 82]])

In [8]:
(x_tf + 2).numpy()
# We can use tf.multiply or tf.add also. Operators are overloaded.

array([[14, 15, 26],
       [23, 34, 43]])

In [9]:
(x_pt + 2).numpy()
# We can use torch.mul or torch.add also. Operators are overloaded.

array([[14, 15, 26],
       [23, 34, 43]], dtype=int64)

In [24]:
A = np.array([[1, 3, 4], [2, 3, 1]])
A

array([[1, 3, 4],
       [2, 3, 1]])

In [25]:
(x + A)

array([[13, 16, 28],
       [23, 35, 42]])

In [26]:
(x_tf + A).numpy()

array([[13, 16, 28],
       [23, 35, 42]])

In [27]:
(x_pt + A).numpy()

array([[13, 16, 28],
       [23, 35, 42]], dtype=int64)

In [28]:
# When we multiply two same dimensional tensors, it is element by element multiplication and not a matrix multiplication.
# Also known as Hadmard multiplication.
(x * A)

array([[12, 39, 96],
       [42, 96, 41]])

In [29]:
(x_tf * A).numpy()

array([[12, 39, 96],
       [42, 96, 41]])

In [30]:
(x_pt * A).numpy()

array([[12, 39, 96],
       [42, 96, 41]], dtype=int64)