In [2]:
import numpy as np
import torch

In [3]:
# Calculate transpose of matrix Y.
Y = torch.tensor([[42, 4, 7, 99], [-99, -3, 17, 22]])
Y

tensor([[ 42,   4,   7,  99],
        [-99,  -3,  17,  22]])

In [4]:
Y = Y.T
Y

tensor([[ 42, -99],
        [  4,  -3],
        [  7,  17],
        [ 99,  22]])

In [5]:
# Calculate Hadamard product of A and B
A = torch.tensor([[25, 10], [-2, 1]])
B = torch.tensor([[-1, 7], [10, 8]])

In [7]:
C = A * B
C

tensor([[-25,  70],
        [-20,   8]])