Reduction - Calculating some of all the elements in a vector.

sigma(xi)
for matrix
sigma(xij)

In [1]:
import numpy as np
import tensorflow as tf
import torch

In [2]:
X = np.array([[12, 13, 24], [21, 32, 41]])
X_pt = torch.tensor([[12, 13, 24], [21, 32, 41]])
X_tf = tf.Variable([[12, 13, 24], [21, 32, 41]])

In [3]:
X.sum()

143

In [8]:
torch.sum(X_pt)

tensor(143)

In [5]:
tf.reduce_sum(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=143>

In [6]:
# Can be calculated along an axis also.
# Perform sum along the column.
X.sum(axis=0)

array([33, 45, 65])

In [7]:
X.sum(axis=1)

array([49, 94])

In [9]:
torch.sum(X_pt, 0)

tensor([33, 45, 65])

In [10]:
torch.sum(X_pt, 1)

tensor([49, 94])

In [11]:
tf.reduce_sum(X_tf, 0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([33, 45, 65])>

In [12]:
tf.reduce_sum(X_tf, 1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([49, 94])>

Other reductions can also be performed along any axes like -
    Maximum
    Minimum
    Mean
    Product