In [10]:
import numpy as np
import tensorflow as tf
import torch

In [8]:
# Array in numpy
x = np.array([[12, 13, 24], [21, 32, 41]])
x

array([[12, 13, 24],
       [21, 32, 41]])

In [9]:
x = x.T
x

array([[12, 21],
       [13, 32],
       [24, 41]])

In [14]:
# Array in PyTorch
x_pt = torch.tensor([[12, 13, 24], [21, 32, 41]])
x_pt.numpy()

array([[12, 13, 24],
       [21, 32, 41]], dtype=int64)

In [18]:
x_pt = x_pt.T
x_pt.numpy()

array([[12, 21],
       [13, 32],
       [24, 41]], dtype=int64)

In [20]:
# Array in TensorFlow
x_tf = tf.Variable([[12, 13, 24], [21, 32, 41]])
x_tf.numpy()

array([[12, 13, 24],
       [21, 32, 41]])

In [21]:
x_tf = tf.transpose(x_tf)
x_tf.numpy()

array([[12, 21],
       [13, 32],
       [24, 41]])