Vector of length 'n' represents a point in an n-dimensional tensor

Creating Vector

In [22]:
import numpy as np
import torch
import tensorflow as tf

x = np.array([25, 2, 6])    # type argument is optional
x
# This array does not have 2 dimensions. It is just and array of size 3. We want to give dimensions to it, we create it in form of matrix. Then only transpose works.

array([25,  2,  6])

In [2]:
len(x)

3

In [3]:
x.shape
# Shape is (3,) because there is no second dimension.

(3,)

In [4]:
type(x)

numpy.ndarray

Transpose Vector

In [5]:
x = x.T
x
# Doesn't do anything.

array([25,  2,  6])

In [14]:
y = np.array([[25, 2, 6]])
y

array([[25,  2,  6]])

In [15]:
y.shape
# Now it's shape is (1,3) and hence we can do transpose operation also.

(1, 3)

In [16]:
y = y.T
y

array([[25],
       [ 2],
       [ 6]])

In [17]:
y.shape

(3, 1)

Zero Vectors -
Vectors consisting of only zeroes.
Have no effect if added to another vector.

In [18]:
z = np.zeros(3)
z

array([0., 0., 0.])

Vectors in PyTorch and TensorFlow

In [28]:
x_pytorch = torch.tensor([[25, 3, 45]])
x_pytorch.shape
# Similar as stated earlier, when defined in matrix style, a vector will have 2-dimensions otherwise not.

torch.Size([1, 3])

In [23]:
x_tensor = tf.Variable([23, 45, 46])
x_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([23, 45, 46])>

In [29]:
x_pytorch = x_pytorch.T
x_pytorch

tensor([[25],
        [ 3],
        [45]])

In [30]:
x_pytorch.shape

torch.Size([3, 1])