C(i,k) = sigma(j)[A(i,j) * B(j,k)]

Number of columns in final matrix is equal to that of B and rows as that of A

Matrix * Vector

In [7]:
import tensorflow as tf
import numpy as np
import torch

In [8]:
A = np.array([[3, 4], [5, 6], [7, 8]])
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [9]:
b = np.array([1, 2])
b

array([1, 2])

In [10]:
np.dot(A, b)

array([11, 17, 23])

In [12]:
A_pt = torch.from_numpy(A)
b_pt = torch.from_numpy(b)
A_pt

tensor([[3, 4],
        [5, 6],
        [7, 8]], dtype=torch.int32)

In [16]:
torch.matmul(A_pt, b_pt)

tensor([11, 17, 23], dtype=torch.int32)

In [17]:
A_tf = tf.Variable([[3, 4], [5, 6], [7, 8]])
b = tf.Variable([1, 2])
A_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [7, 8]])>

In [18]:
# In TensorFlow we need to specify what kind of multiplication we're performing.
tf.linalg.matvec(A_tf, b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 17, 23])>

Matrix * Matrix

In [19]:
C = np.array([[1, 9], [2, 0]])
C

array([[1, 9],
       [2, 0]])

In [20]:
np.dot(A, C)

array([[11, 27],
       [17, 45],
       [23, 63]])

In [21]:
C_pt = torch.from_numpy(C)
torch.linalg.matmul(A_pt, C_pt)

tensor([[11, 27],
        [17, 45],
        [23, 63]], dtype=torch.int32)

In [25]:
C_tf = tf.Variable([[1, 9], [2, 0]])
tf.matmul(A_tf, C_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 27],
       [17, 45],
       [23, 63]])>

In [26]:
tf.linalg.matmul(A_tf, C_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 27],
       [17, 45],
       [23, 63]])>