Symmetric Matrix -> n(rows) = n(columns)
A = A(transpose)

Identity Matrix -> A symmetric matrix where all diagonal elements are 1 and all other elements are 0.

In [3]:
import numpy as np
import torch
X = np.array([[1, 2, 3], [2, 5, 8], [3, 8, 0]])
X

array([[1, 2, 3],
       [2, 5, 8],
       [3, 8, 0]])

In [4]:
X.T == X

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
I_pt = torch.tensor([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
I_pt

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [6]:
x_pt = torch.tensor([10, 43, 44])
x_pt

tensor([10, 43, 44])

In [7]:
torch.matmul(I_pt, x_pt)

tensor([10, 43, 44])